import Layout from "@/components/Layout";
import Head from "next/head";
import { search } from 'services/search.js'
export default function Component({ query }) {
  return (
    <>
      <Head>
        <title>XKCD -Results for {query} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <h1>Resultados para {query}</h1> <style jsx>{""}</style>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  const { query } = context;
  const { q = "" } = query;

  const { results } = await search({query: q})
 
 
  return {
    props: {
      query: q,
      results
    },
  };
}
