import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import fs from "node:fs/promises";
import Layout from "@/components/Layout.js";
import { useI18N } from 'context/i18n.js'


export default function Home({ latestComics }) {
const { t } = useI18N();

  return (
    <>
      <Head>
        <title>XKCD -Comic for developers </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h2 className="text-3xl font-bold text-center mb-10">{t('LATEST_COMICS')}</h2>
        <section className="grid grid-cols-1 gap-2 max-w-md  m-auto sm:grid-cols-2 md:grid-cols-3">
          {latestComics.map((comic) => {
            return (
              <Link href={`/comic/${comic.id}`} key={comic.id} className=" ">
                <h3 className="font-bold text-sm text-center">{comic.title}</h3>
                <Image
                  width={comic.width}
                  height={comic.height}
                  src={comic.img}
                  alt={comic.alt}
                  className="mb-4 pb-4 m-auto "
                />
              </Link>
            );
          })}
        </section>
      </Layout>
    </>
  );
}

export async function getStaticProps(context) {
  const files = await fs.readdir("./comics");
  const latestComicsFiles = files.slice(-8, files.length);

  const promisesReadFiles = latestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, "utf-8");
    return JSON.parse(content);
  });

  const latestComics = await Promise.all(promisesReadFiles);
  return {
    props: {
      latestComics,
    },
  };
}
